import PDFDocument from 'pdfkit';

export const generatePayslipPdf = (payrollRecord, employeeProfile, res) => {
  const doc = new PDFDocument({ margin: 40, size: 'A4' });

  // Stream PDF directly to client response
  doc.pipe(res);

  // Styling Constants
  const primaryColor = '#00C896';
  const darkNavy = '#0D1117';
  const grayText = '#4A5568';
  const borderGray = '#E2E8F0';

  // 1. Header Banner
  doc.rect(40, 40, 515, 65).fill('#161D27');
  doc.fillColor(primaryColor).fontSize(20).text('DAYFLOW HR', 60, 55, { bold: true });
  doc.fillColor('#94A3B8').fontSize(9).text('Every workday, perfectly aligned.', 60, 80);
  doc.fillColor('#FFFFFF').fontSize(14).text(`SALARY PAYSLIP - ${payrollRecord.month.toUpperCase()}`, 300, 65, { align: 'right' });

  doc.moveDown(3);

  // 2. Employee & Company Info Grid
  const startY = 125;
  doc.fillColor(darkNavy).fontSize(11).text('Employee Details:', 40, startY, { bold: true });
  doc.fillColor(grayText).fontSize(9);
  doc.text(`Employee Name: ${payrollRecord.employeeName || employeeProfile.fullName}`, 40, startY + 18);
  doc.text(`Employee ID: ${payrollRecord.employeeId}`, 40, startY + 32);
  doc.text(`Designation: ${payrollRecord.designation || (employeeProfile.jobDetails && employeeProfile.jobDetails.designation) || 'Staff'}`, 40, startY + 46);
  doc.text(`Department: ${payrollRecord.department || (employeeProfile.jobDetails && employeeProfile.jobDetails.department) || 'Engineering'}`, 40, startY + 60);

  doc.fillColor(darkNavy).fontSize(11).text('Payment Information:', 320, startY, { bold: true });
  doc.fillColor(grayText).fontSize(9);
  doc.text(`Pay Period: ${payrollRecord.month}`, 320, startY + 18);
  doc.text(`Payment Date: ${payrollRecord.paymentDate || '2026-08-31'}`, 320, startY + 32);
  doc.text(`Status: ${payrollRecord.status}`, 320, startY + 46);
  doc.text(`Payment Method: ${payrollRecord.paymentMethod || 'Direct Deposit'}`, 320, startY + 60);

  // Divider
  doc.moveTo(40, startY + 85).lineTo(555, startY + 85).strokeColor(borderGray).stroke();

  // 3. Earnings and Deductions Table
  const tableTop = startY + 105;

  // Earnings Header
  doc.rect(40, tableTop, 245, 24).fill('#F1F5F9');
  doc.fillColor('#1E293B').fontSize(10).text('Earnings', 50, tableTop + 6, { bold: true });
  doc.text('Amount (INR)', 200, tableTop + 6, { bold: true, align: 'right' });

  // Deductions Header
  doc.rect(310, tableTop, 245, 24).fill('#F1F5F9');
  doc.fillColor('#1E293B').fontSize(10).text('Deductions', 320, tableTop + 6, { bold: true });
  doc.text('Amount (INR)', 470, tableTop + 6, { bold: true, align: 'right' });

  // Rows
  const earnings = [
    { label: 'Basic Salary', amount: `INR ${payrollRecord.basic.toLocaleString()}` },
    { label: 'House Rent Allowance (HRA)', amount: `INR ${payrollRecord.hra.toLocaleString()}` },
    { label: 'Transport Allowance', amount: `INR ${payrollRecord.transport.toLocaleString()}` },
    { label: 'Medical Allowance', amount: `INR ${payrollRecord.medical.toLocaleString()}` }
  ];

  const deductions = [
    { label: 'Income Tax Deduction', amount: `INR ${payrollRecord.taxDeduction.toLocaleString()}` },
    { label: 'Provident Fund (PF)', amount: `INR ${payrollRecord.pfDeduction.toLocaleString()}` }
  ];

  let currentY = tableTop + 32;
  doc.fillColor(grayText).fontSize(9);

  earnings.forEach((item, i) => {
    doc.text(item.label, 50, currentY);
    doc.text(item.amount, 150, currentY, { width: 135, align: 'right' });

    if (deductions[i]) {
      doc.text(deductions[i].label, 320, currentY);
      doc.text(deductions[i].amount, 420, currentY, { width: 135, align: 'right' });
    }
    currentY += 20;
  });

  // Gross & Total Deductions Subtotals
  doc.moveTo(40, currentY + 10).lineTo(555, currentY + 10).strokeColor(borderGray).stroke();
  currentY += 20;

  doc.fillColor('#1E293B').fontSize(10);
  doc.text('Gross Earnings:', 50, currentY, { bold: true });
  doc.text(`INR ${payrollRecord.gross.toLocaleString()}`, 150, currentY, { width: 135, bold: true, align: 'right' });

  const totalDeductions = payrollRecord.taxDeduction + payrollRecord.pfDeduction;
  doc.text('Total Deductions:', 320, currentY, { bold: true });
  doc.text(`INR ${totalDeductions.toLocaleString()}`, 420, currentY, { width: 135, bold: true, align: 'right' });

  // 4. Net Salary Highlight Box
  currentY += 35;
  doc.rect(40, currentY, 515, 45).fill('#F0FDF4');
  doc.rect(40, currentY, 515, 45).strokeColor('#86EFAC').stroke();
  doc.fillColor('#166534').fontSize(12).text('NET TAKE-HOME SALARY:', 60, currentY + 15, { bold: true });
  doc.fillColor('#15803D').fontSize(16).text(`INR ${payrollRecord.netSalary.toLocaleString()}`, 260, currentY + 12, { width: 275, bold: true, align: 'right' });

  // 5. Footer & Authenticity
  const footerY = 560;
  doc.fillColor('#94A3B8').fontSize(8);
  doc.text('This is a computer-generated payslip generated by Dayflow HR System and requires no physical signature.', 40, footerY, { align: 'center' });
  doc.text('Confidential - For recipient use only. Contact hr@dayflow.com for any discrepancies.', 40, footerY + 14, { align: 'center' });

  doc.end();
};
